# git-cliff configuration file
# https://git-cliff.org/docs/configuration

[changelog]
# changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""

# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat = "v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}\
### {{ group }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit.url | default(value="") }}))
{% endfor %}\
{% endfor %}\
"""
# remove the leading and trailing whitespace from the template
trim = true

[git]
# parse commits between these tags
# range = "HEAD~5..HEAD"
# show unreleased changes
unreleased = true
# commit parsing
conventional_commits = true
filter_unmerged = true

# Major changes
[[git.commit_parsers]]
message = "^feat!(.+)"
group = "Breaking Changes"
default_branch = "main"
# filter_unmerged = true

# Features
[[git.commit_parsers]]
message = "^feat(.+)"
group = "Features"
default_branch = "main"

# Bug fixes
[[git.commit_parsers]]
message = "^fix(.+)"
group = "Bug Fixes"
default_branch = "main"

# Refactoring
[[git.commit_parsers]]
message = "^refactor(.+)"
group = "Refactoring"
default_branch = "main"

# Documentation
[[git.commit_parsers]]
message = "^docs(.+)"
group = "Documentation"
default_branch = "main"

# Tests
[[git.commit_parsers]]
message = "^test(.+)"
group = "Testing"
default_branch = "main"

# Build / CI
[[git.commit_parsers]]
message = "^build(.+)|^ci(.+)"
group = "Build / CI"
default_branch = "main"

# Other commits
[[git.commit_parsers]]
message = ".*"
group = "Other Changes"
default_branch = "main"

[[git.tagparsers]]
# treat tags with a `v` prefix as semantic version tags
pattern = "^v(.*)$"
# semantic version parser - supports v1.0.0, v1.0.0-rc1, v1.0.0-alpha, v1.0.0-beta, v1.0.0-preview, v1.0.0-dev, etc.
semver = "v(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(-(?P<prerelease>(rc|alpha|beta|preview|dev)\\d*))?$"
